openapi: 3.0.1
info:
  title: MeTAPyquod Server
  description: This is an example search service implemented with the MeTA toolkit
    and metapy bindings.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: MeTA Toolkit
  url: https://meta-toolkit.org
servers:
- url: http://localhost:8080/
tags:
- name: search
  description: Search the index
paths:
  /search:
    post:
      tags:
      - search
      summary: Retrieve results for a given query
      operationId: search_post
      requestBody:
        description: Search parameters
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryParams'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
                x-content-type: application/json
        "405":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-swagger-router-controller: metapyquod.web.controllers.search_controller
      x-openapi-router-controller: swagger_server.controllers.search_controller
  /search/{query}:
    get:
      tags:
      - search
      summary: Retrieve results for a given query
      operationId: search_get
      parameters:
      - name: query
        in: path
        description: Query content
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: top
        in: query
        description: Return this many results (pagination)
        required: false
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          default: 10
      - name: skip
        in: query
        description: Skip this many results (pagination)
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          default: 0
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
                x-content-type: application/json
        "400":
          description: Invalid query
          content: {}
      x-swagger-router-controller: metapyquod.web.controllers.search_controller
      x-openapi-router-controller: swagger_server.controllers.search_controller
  /click/{query}/{url}:
    get:
      tags:
      - feedback
      summary: Click-through redirector for capturing implicit feedback
      operationId: click_get
      parameters:
      - name: query
        in: path
        description: Original query content
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: url
        in: path
        description: URL of selected result
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "302":
          description: successful operation
          headers:
            Location:
              description: The destination URL
              style: simple
              explode: false
              schema:
                type: string
        "400":
          description: Invalid query or URL
          content: {}
      x-swagger-router-controller: metapyquod.web.controllers.feedback_controller
      x-openapi-router-controller: swagger_server.controllers.feedback_controller
  /telemetry/recent:
    get:
      tags:
      - telemetry
      summary: Get the most recently indexed documents.
      operationId: telemetry_recent_get
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
                x-content-type: application/json
      x-swagger-router-controller: metapyquod.web.controllers.telemetry_controller
      x-openapi-router-controller: swagger_server.controllers.telemetry_controller
  /telemetry/stats:
    get:
      tags:
      - telemetry
      summary: Get statistics about the search index.
      operationId: telemetry_stats_get
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResult'
      x-swagger-router-controller: metapyquod.web.controllers.telemetry_controller
      x-openapi-router-controller: swagger_server.controllers.telemetry_controller
components:
  schemas:
    QueryParams:
      type: object
      properties:
        query:
          type: string
          description: Query content
        top:
          type: integer
          description: Return this many results (pagination)
          format: int32
          default: 10
        skip:
          type: integer
          description: Skip this many results (pagination)
          format: int32
          default: 0
      xml:
        name: Order
    QueryResult:
      type: object
      properties:
        doc_id:
          type: integer
          description: The internal index document ID
          format: int64
        url:
          type: string
          description: The URL of the page matching the query
          format: url
        score:
          type: number
          description: Score assigned for the document by the ranker
        title:
          type: string
          description: A title (e.g. from an HTML document) or other derived label
      example:
        score: 6.027456183070403
        doc_id: 0
        url: http://example.com/aeiou
    StatsResult:
      type: object
      properties:
        num_docs:
          type: integer
          description: The number of documents currently in the index
          format: int64
        num_terms:
          type: integer
          description: The number of terms currently in the index
          format: int64
        disk_size:
          type: integer
          description: Size of the index in bytes
          format: int64
      example:
        num_docs: 0
        num_terms: 6
        disk_size: 1

