openapi: 3.0.1
info:
  title: MeTAPyquod Server
  description: 'This is an example search service implemented with the MeTA toolkit and metapy bindings.'
  #termsOfService: http://...
  #contact:
  #  email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: MeTA Toolkit
  url: https://meta-toolkit.org
servers:
- url: http://localhost:8080/
tags:
- name: search
  description: Search the index
paths:
  /search:
    post:
      tags:
      - search
      summary: Retrieve results for a given query
      operationId: searchPost
      requestBody:
        description: Search parameters
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryParams'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-swagger-router-controller: "metapyquod.web.controllers.search_controller"

  /search/{query}:
    get:
      tags:
      - search
      summary: Retrieve results for a given query
      operationId: searchGet
      parameters:
      - name: query
        in: path
        description: Query content
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: top
        in: query
        description: Return this many results (pagination)
        schema:
          type: integer
          minimum: 1
          default: 10
      - name: skip
        in: query
        description: Skip this many results (pagination)
        schema:
          type: integer
          minimum: 0
          default: 0
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
        400:
          description: Invalid query
          content: {}
      x-swagger-router-controller: "metapyquod.web.controllers.search_controller"

  /click/{query}/{url}:
    get:
      tags:
      - feedback
      summary: Click-through redirector for capturing implicit feedback
      operationId: clickGet
      parameters:
      - name: query
        in: path
        description: Original query content
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: url
        in: path
        description: URL of selected result
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        302:
          description: successful operation
          headers:
            Location:
              schema: 
                type: string
              description: The destination URL
        400:
          description: Invalid query or URL
          content: {}
      x-swagger-router-controller: "metapyquod.web.controllers.feedback_controller"

  /telemetry/recent:
    get:
      tags:
      - telemetry
      summary: Get the most recently indexed documents.
      operationId: telemetryRecentGet
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
      x-swagger-router-controller: "metapyquod.web.controllers.telemetry_controller"

  /telemetry/stats:
    get:
      tags:
      - telemetry
      summary: Get statistics about the search index.
      operationId: telemetryStatsGet
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResult'
      x-swagger-router-controller: "metapyquod.web.controllers.telemetry_controller"
                
components:
  schemas:
    QueryParams:
      type: object
      properties:
        query:
          type: string
          description: Query content
        top:
          type: integer
          format: int32
          default: 10
          description: Return this many results (pagination)
        skip:
          type: integer
          format: int32
          default: 0
          description: Skip this many results (pagination)
      xml:
        name: Order
    QueryResult:
      type: object
      properties:
        doc_id:
          type: integer
          format: int64
          description: The internal index document ID
        url:
          type: string
          format: url
          description: The URL of the page matching the query
        score:
          type: number
          description: Score assigned for the document by the ranker
        title:
          type: string
          description: A title (e.g. from an HTML document) or other derived label
    StatsResult:
      type: object
      properties:
        num_docs:
          type: integer
          format: int64
          description: The number of documents currently in the index
        num_terms:
          type: integer
          format: int64
          description: The number of terms currently in the index
        disk_size:
          type: integer
          format: int64
          description: Size of the index in bytes
